jobs:
  include:

  - language: java
    jdk: openjdk8
    cache:
      directories:
        - $HOME/.m2

    before_install: cd backend\spring-boot
    install: true

    script: mvn -B test  # mvn clean install is működne

    deploy:
      skip_cleanup: true
      provider: heroku
      api_key:
        secure: "8faf5f01-f8d3-4df8-a0a8-f62fbf2f10cf"
      app: backend4spring-boot
      on: main
